import type { DiscountType } from '../enums/discountType';
import type { InvoiceStatus } from '../enums/invoiceStatus';
import type { InvoiceType } from '../enums/invoiceType';
import type { InvoiceItemTaxType, InvoiceTaxType } from '../enums/taxType';

export interface DiscountForm {
  discountType?: DiscountType;
  discountAmount?: number;
  discountRate?: number;
  discountName?: string;
}
export interface InvoicePayment {
  id: number;
  parentInvoiceId: number;
  amountCents: number;
  paidAt: string;
  paymentMethod: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface InvoiceItem {
  id?: number;
  parentInvoiceId?: number;
  itemId: number;
  itemNameSnapshot: string;
  unitPriceCentsSnapshot: number;
  itemDescriptionSnapshot?: string;
  unitNameSnapshot?: string;
  categoryNameSnapshot?: string;
  quantity: number;
  createdAt?: string;
  updatedAt?: string;
  taxName?: string;
  taxRate: number;
  taxType?: InvoiceItemTaxType;
}

export interface Invoice {
  id: number;
  invoiceType: InvoiceType;
  convertedFromQuotationId?: number;
  businessId: number;
  clientId: number;
  currencyId: number;
  createdAt: string;
  updatedAt: string;
  issuedAt: string;
  dueDate?: string;
  invoiceNumber: string;
  isArchived: boolean;
  status: InvoiceStatus;
  customerNotes?: string;
  thanksNotes?: string;
  termsConditionNotes?: string;
  discountName?: string;
  businessNameSnapshot: string;
  businessDescriptionSnapshot?: string;
  businessAddressSnapshot?: string;
  businessRoleSnapshot?: string;
  clientShortName: string;
  invoicePrefixSnapshot?: string;
  invoiceSuffixSnapshot?: string;
  businessShortName: string;
  businessEmailSnapshot?: string;
  businessPhoneSnapshot?: string;
  businessWebsiteSnapshot?: string;
  businessAdditionalSnapshot?: string;
  businessPaymentInformationSnapshot?: string;
  businessLogoSnapshot?: Uint8Array;
  businessFileSizeSnapshot?: number;
  businessFileTypeSnapshot?: string;
  businessFileNameSnapshot?: string;
  clientNameSnapshot: string;
  clientAddressSnapshot?: string;
  clientDescriptionSnapshot?: string;
  clientEmailSnapshot?: string;
  clientPhoneSnapshot?: string;
  clientCodeSnapshot?: string;
  clientAdditionalSnapshot?: string;
  currencyCodeSnapshot: string;
  currencySymbolSnapshot: string;
  currencySubunitSnapshot: number;
  discountType?: DiscountType;
  discountAmountCents: number;
  discountPercent: number;
  shippingFeeCents: number;
  taxName?: string;
  taxRate: number;
  taxType?: InvoiceTaxType;
  invoicePayments: InvoicePayment[];
  invoiceItems: InvoiceItem[];
  currencyFormat: string;
}

export interface InvoiceAdd {
  invoiceType?: InvoiceType;
  convertedFromQuotationId?: number;
  businessId?: number;
  clientId?: number;
  currencyId?: number;
  issuedAt?: string;
  dueDate?: string;
  invoiceNumber?: string;
  isArchived?: boolean;
  status?: InvoiceStatus;
  customerNotes?: string;
  thanksNotes?: string;
  invoicePrefixSnapshot?: string;
  invoiceSuffixSnapshot?: string;
  termsConditionNotes?: string;
  discountName?: string;
  businessNameSnapshot?: string;
  businessDescriptionSnapshot?: string;
  businessAddressSnapshot?: string;
  businessRoleSnapshot?: string;
  clientShortName?: string;
  businessShortName?: string;
  businessEmailSnapshot?: string;
  businessPhoneSnapshot?: string;
  businessWebsiteSnapshot?: string;
  businessAdditionalSnapshot?: string;
  businessPaymentInformationSnapshot?: string;
  businessLogoSnapshot?: string | null;
  businessFileSizeSnapshot?: number;
  businessFileTypeSnapshot?: string;
  businessFileNameSnapshot?: string;
  clientNameSnapshot?: string;
  clientAddressSnapshot?: string;
  clientDescriptionSnapshot?: string;
  clientEmailSnapshot?: string;
  clientPhoneSnapshot?: string;
  clientCodeSnapshot?: string;
  clientAdditionalSnapshot?: string;
  currencyCodeSnapshot?: string;
  currencySymbolSnapshot?: string;
  currencySubunitSnapshot?: number;
  discountType?: DiscountType;
  discountAmountCents?: number;
  discountPercent?: number;
  shippingFeeCents?: number;
  taxName?: string;
  taxRate?: number;
  taxType?: InvoiceTaxType;
  invoicePayments?: InvoicePayment[];
  invoiceItems?: InvoiceItem[];
  currencyFormat?: string;
}

export interface InvoiceUpdate extends InvoiceAdd {
  id: number;
}

export interface InvoiceFromData {
  id?: number;
  invoiceType?: InvoiceType;
  convertedFromQuotationId?: number;
  businessId?: number;
  clientId?: number;
  currencyId?: number;
  issuedAt?: string;
  dueDate?: string;
  invoiceNumber?: string;
  isArchived?: boolean;
  status?: InvoiceStatus;
  customerNotes?: string;
  thanksNotes?: string;
  invoicePrefixSnapshot?: string;
  invoiceSuffixSnapshot?: string;
  termsConditionNotes?: string;
  discountName?: string;
  businessNameSnapshot?: string;
  businessDescriptionSnapshot?: string;
  businessAddressSnapshot?: string;
  businessRoleSnapshot?: string;
  clientShortName?: string;
  businessShortName?: string;
  businessEmailSnapshot?: string;
  businessPhoneSnapshot?: string;
  businessWebsiteSnapshot?: string;
  businessAdditionalSnapshot?: string;
  businessPaymentInformationSnapshot?: string;
  businessLogoSnapshot?: string | null;
  businessFileSizeSnapshot?: number;
  businessFileTypeSnapshot?: string;
  businessFileNameSnapshot?: string;
  clientNameSnapshot?: string;
  clientAddressSnapshot?: string;
  clientDescriptionSnapshot?: string;
  clientEmailSnapshot?: string;
  clientPhoneSnapshot?: string;
  clientCodeSnapshot?: string;
  clientAdditionalSnapshot?: string;
  currencyCodeSnapshot?: string;
  currencySymbolSnapshot?: string;
  currencySubunitSnapshot?: number;
  discountType?: DiscountType;
  discountAmountCents?: number;
  discountPercent?: number;
  shippingFeeCents?: number;
  taxName?: string;
  taxRate?: number;
  taxType?: InvoiceTaxType;
  invoicePayments?: InvoicePayment[];
  invoiceItems?: InvoiceItem[];
  currencyFormat?: string;
}

export interface InvoicesModified {
  id: number;
  invoiceType: InvoiceType;
  convertedFromQuotationId?: number;
  businessId: number;
  clientId: number;
  currencyId: number;
  createdAt: string;
  updatedAt: string;
  issuedAt: string;
  dueDate?: string;
  invoiceNumber: string;
  isArchived: boolean;
  status: InvoiceStatus;
  customerNotes?: string;
  thanksNotes?: string;
  termsConditionNotes?: string;
  discountName?: string;
  businessNameSnapshot: string;
  invoicePrefixSnapshot?: string;
  invoiceSuffixSnapshot?: string;
  businessDescriptionSnapshot?: string;
  businessAddressSnapshot?: string;
  businessRoleSnapshot?: string;
  clientShortName: string;
  businessShortName: string;
  businessEmailSnapshot?: string;
  businessPhoneSnapshot?: string;
  businessWebsiteSnapshot?: string;
  businessAdditionalSnapshot?: string;
  businessPaymentInformationSnapshot?: string;
  businessLogoSnapshot?: string | null;
  businessFileSizeSnapshot?: number;
  businessFileTypeSnapshot?: string;
  businessFileNameSnapshot?: string;
  clientNameSnapshot: string;
  clientAddressSnapshot?: string;
  clientDescriptionSnapshot?: string;
  clientEmailSnapshot?: string;
  clientPhoneSnapshot?: string;
  clientCodeSnapshot?: string;
  clientAdditionalSnapshot?: string;
  currencyCodeSnapshot: string;
  currencySymbolSnapshot: string;
  currencySubunitSnapshot: number;
  discountType?: DiscountType;
  discountAmountCents: number;
  discountPercent: number;
  shippingFeeCents: number;
  taxName?: string;
  taxRate: number;
  taxType?: InvoiceTaxType;
  invoicePayments: InvoicePayment[];
  invoiceItems: InvoiceItem[];
  currencyFormat: string;
}
